blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/vahiiiid/go-rest-api-boilerplate/blob/main/README.md
    about: Check the README for setup instructions and usage examples
  - name: 💬 Discussions
    url: https://github.com/vahiiiid/go-rest-api-boilerplate/discussions
    about: Ask questions and discuss ideas with the community